### ISSUE TITLE
Misconfigured Dual Stack (IPv6 not responding) causes issues with non-happy-eyeballs clients

### ISSUE THREAD

**Issue by ctheune** [public-transport/transport.rest#23] opened 2024-01-03 15:47 UTC
I've started talking to the API using Python's `requests` library and noticed that it takes a long time to connect. There is a `AAAA` record for `v6.db.transport.rest` so this gets talked to with a higher priority until the non-responsiveness falls back to IPv4 after around 60-90 seconds.

I'm not quite sure whether this is broken on your provider's side or the service itself. Routing looks like this and isn't in the target network but close:

```
chazzzzz (2003:a:745:af0a:3028:8704:ffe1:4d34) -> v6.db.transport.rest (2a01:4f8:c012:91b7::)                                                                                           2024-01-03T16:46:25+0100
Keys:  Help   Display mode   Restart statistics   Order of fields   quit

                             Last 179 pings
 1. 2003:a:745:af0a::1                                                                                                                                                                             ...?.........
 2. 2003:0:1701:a409::1                                                                                                                                                                            ....>........
 3. 2003:0:1701:e400::2                                                                                                                                                                            .>>>.........
 4. 2003:0:1902:4000::1                                                                                                                                                                            .............
 5. 2003:0:f00::209                                                                                                                                                                                .............
 6. 2a01:4f8:0:3::611                                                                                                                                                                              ............
 7. (waiting for reply)                                                                                                                                                                            ????????????
 ```

**Comment by traines-source** [comment] 2024-11-16 13:36
Duplicate of #20 , should now finally work again.

**Closed by traines-source** 2024-11-16 13:36 UTC
